### PR TITLE
Fix syntax errors

### LINKED ISSUE #21: SourceShell editor does not work
When attempting to open shell files, the editor does not appear. Instead, there is an error message: `Failed to create the part's controls`

Below is the stack trace. This error appeared starting with Eclipse 2023-09. LiclipseText appears to work just fine with 2023-06.

This error applies to several other editors including the Generic Text Editor.

```
java.lang.NoSuchFieldError: numRegs
	at org.eclipse.tm4e.core.internal.oniguruma.OnigResult.count(OnigResult.java:50)
	at org.eclipse.tm4e.core.internal.oniguruma.OnigSearcher.search(OnigSearcher.java:41)
	at org.eclipse.tm4e.core.internal.oniguruma.OnigScanner.findNextMatchSync(OnigScanner.java:29)
	at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.matchRule(LineTokenizer.java:262)
	at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.matchRuleOrInjections(LineTokenizer.java:284)
	at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:109)
	at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:100)
	at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:521)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.tokenize(Grammar.java:242)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.tokenizeLine(Grammar.java:194)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipseDocumentPartitionerTmCache.tokenizeLine(LiClipseDocumentPartitionerTmCache.java:376)
	at org.brainwy.liclipsetext.editor.partitioning.ScannerRange.tokenizeLine(ScannerRange.java:561)
	at org.brainwy.liclipsetext.editor.common.partitioning.tm4e.Tm4ePartitionScanner.nextToken(Tm4ePartitionScanner.java:127)
	at org.brainwy.liclipsetext.editor.partitioning.ScannerRange.nextToken(ScannerRange.java:111)
	at org.brainwy.liclipsetext.editor.common.partitioning.reader.SubTokensTokensProvider.nextToken(SubTokensTokensProvider.java:85)
	at org.brainwy.liclipsetext.editor.common.partitioning.reader.SubTokensTokensProvider.getTokens(SubTokensTokensProvider.java:140)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipseDamagerRepairer.internalCreatePresentation(LiClipseDamagerRepairer.java:189)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipseDamagerRepairer.createPresentation(LiClipseDamagerRepairer.java:153)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipsePresentationReconciler$ProcessRepairListJob.repairDamage(LiClipsePresentationReconciler.java:834)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipsePresentationReconciler$ProcessRepairListJob.doRun(LiClipsePresentationReconciler.java:748)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipsePresentationReconciler.applyPresentation(LiClipsePresentationReconciler.java:676)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipsePresentationReconciler.processDamage(LiClipsePresentationReconciler.java:1004)
	at org.brainwy.liclipsetext.editor.common.partitioning.LiClipsePresentationReconciler$InternalListener.inputDocumentChanged(LiClipsePresentationReconciler.java:177)
	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2849)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2890)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:682)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:368)
	at org.brainwy.liclipsetext.editor.common.LiClipseSourceViewer.setDocument(LiClipseSourceViewer.java:94)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:632)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3980)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3472)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:445)
	at org.brainwy.liclipsetext.editor.common.BaseLiClipseEditor.createPartControl(BaseLiClipseEditor.java:148)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:971)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:936)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:142)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:313)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:105)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:661)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:625)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:796)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1270)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3233)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:3123)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3121)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3091)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3082)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:548)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:508)
	at org.eclipse.ui.actions.OpenFileAction.openFile(OpenFileAction.java:103)
	at org.eclipse.ui.actions.OpenSystemEditorAction.run(OpenSystemEditorAction.java:96)
	at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:215)
	at org.eclipse.ui.navigator.CommonNavigatorManager$1.open(CommonNavigatorManager.java:183)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:801)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:798)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1121)
	at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:452)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:296)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

```

### PR DESCRIPTION
**Pull request by zevlee**
Implement upstream t4me changes and their equivalents wherever used in plugin. Fixes https://github.com/fabioz/LiClipseText/issues/21

### CODE REVIEW

**Comment by zevlee** [comment]
I'm personally unsure if I implemented the change at line 74 properly. I changed the line from https://github.com/fabioz/LiClipseText/blob/c91ce64b07e58d0b96204ea9fbfc8695ce748fee/plugins/org.brainwy.liclipsetext.editor/src/org/brainwy/liclipsetext/editor/regexp/CharsRegion.java#L74
to
```java
if (groupId >= region.getBeg(groupId)) {
```

**Comment by zevlee** [comment]
I'm personally unsure if I implemented the change at line 74 properly. I changed the line from https://github.com/fabioz/LiClipseText/blob/c91ce64b07e58d0b96204ea9fbfc8695ce748fee/plugins/org.brainwy.liclipsetext.editor/src/org/brainwy/liclipsetext/editor/regexp/CharsRegion.java#L74
to
```java
        if (groupId >= region.getNumRegs()) {
```

**Comment by zevlee** [comment]
Keep in mind that there is plenty that has changed with the upstream t4me repository. This pull request is simply one part of a larger upstream change.

**Comment by fabioz** [comment]
Hello @zevlee I saw your PR, but I'm still unsure whether to apply it as is... Also, I'm not sure I follow the issue you have.

i.e.: the code should be vendored in https://github.com/fabioz/LiClipseText/tree/master/plugins/org.brainwy.liclipsetext.editor/tm4e_src. Are you saying that you have conflicts when tm4e is also installed?

The plugins structure/classloaders from should make sure that even if the same namespace is used errors shouldn't appear, but maybe something from tm4e is splashing into eclipse itself for you to have errors? If that's the case the actual fix would be renaming the org/eclipse/tm4e to something different (maybe `org/tm4e_vendored` or something on those lines).

Note that I'm not against changing the vendoring to bring up the changes from the latest version (but then I guess I'd like to bring all the changes at once...).

**Comment by zevlee** [comment]
After looking back over the code, I realized that the issue was being caused by improper syntax for the class `org.joni.Region`. The code can be found [here](https://github.com/jruby/joni/blob/master/src/org/joni/Region.java). All the changes in this pull request pertain to updating the syntax to match what is used in `org.joni.Region`.

As such, a full merge from `tm4e` is unneeded to fix https://github.com/fabioz/LiClipseText/issues/21. I would still like to work on merging upstream tm4e, but will handle that in a separate pull request. In the meantime, I think this PR should be good to go.

**Comment by fabioz** [comment]
@zevlee I'm still not completely sure I follow... `org.joni` should also be versioned in https://github.com/fabioz/LiClipseText/blob/master/plugins/org.brainwy.liclipsetext.editor/META-INF/MANIFEST.MF#L32, so, this update would break things when used with that version...

**Comment by zevlee** [comment]
The only available version for `org.joni` appears to be 2.2.1, which is causing issues. I installed Eclipse 2023-06 and saw that the problem in https://github.com/fabioz/LiClipseText/issues/21 exists in that version too.

**Comment by fabioz** [comment]
Humm, `org.joni` from https://download.eclipse.org/tools/orbit/downloads/drops/R20230531010532/ is actually `2.1.11`.

I guess this can be updated, but then the manifest needs to point to the new version or we may need to vendor it so that it works on older versions of Eclipse.

**Comment by fabioz** [comment]
Maybe vendoring instead of trying to rely on an installed version is better in this case (so, downloading the jar and using that inside the plugin).

**Comment by fabioz** [comment]
p.s.: I'm ok with using the newer version and API, but it shouldn't break on older versions...

**Comment by zevlee** [comment]
I added a second commit which vendors the `org.joni` version 2.2.1 package. Accordingly, I removed the plugin dependency from the manifest.

This should ensure compatibility with older versions of Eclipse. I personally tested with Eclipse 2022-09 and 2023-09 and both now work.

**Comment by zevlee** [comment]
@fabioz Do you want me to also update the version using the `update_version.py` script?

**Comment by fabioz** [comment]
Thank you very much for the changes, it's really a step in the right direction, but when I mean vendoring, I didn't mean vendor the whole code, just the jar (it's easier to update afterwards and we shouldn't copy the code unless we actually need to fork it because changes are needed).

In Eclipse plugins, you can just specify a jar and use it internally (without other plugins seeing it), so, the idea is that the joni `.jar` would be dowloaded and placed in a `/lib` folder (it can be downloaded from https://repo1.maven.org/maven2/org/jruby/joni/joni/2.2.1/), then it can be added to the runtime classpath.

This is done in `org.brainwy.liclipsetext.shared_core` with snakeyaml, so, you can use it as an example (p.s.: no need to add its packages to the exported packages in the joni case):

image

Also, the rename of the tm4e folder should be done as a separate PR (as it's really a separate thing) -- the tm4e isn't used as a whole because we just use a subset of it (see the comments in the README.txt inside of `tm4e_src` if you're interested in it).

p.s.: I'm sorry for the additional work I'm putting you through to get this in (I know that sometimes is really annoying), but I hope you see that the changes are reasonable...

**Comment by zevlee** [comment]
> p.s.: I'm sorry for the additional work I'm putting you through to get this in (I know that sometimes is really annoying), but I hope you see that the changes are reasonable...

No worries! I appreciate your patience and that you took the time to help me understand what to do. I believe the pull request should be ready now. I tested it and it appears to work on the current Eclipse version and older ones too.

**Comment by fabioz** [comment]
Thanks for the fix! I've just merged it.

**Pull request merged**
