### PR TITLE
Support for generic editor extensions

### PR DESCRIPTION
**Pull request by mickaelistria**
This contribute Liclipse based extensions to generic Text Editor.
Most of the work is to allow to plug the partitionner during/after
editor initialization.

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496117
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by paulvi** [comment]
Looking at [Bug 497871 - Provide a Generic and extensible Text Editor](https://bugs.eclipse.org/bugs/show_bug.cgi?id=497871)
I don't see @fabioz participating

**Comment by fabioz** [comment]
Hi Mickael,

Sorry for the delay -- it seems that github did not send me e-mails from this bug (for some reason it didn't register me to hear it  -- really odd that creating the repo I wasn't registered by default, but hopefully I should receive e-mails from now on).

A question: I thought that the idea was that the generic text editor would already have another default implementation, so, do you think it makes sense adding this to LiClipseText (especially given that when installing it it'll already set itself as the default)?

**Comment by mickaelistria** [comment]
The generic editor aims at providing no default implementation and should support multiple implementations (either by aggregating the "value" of the different extension or by picking one - automatically or via user settings).
From LicLipseText perspective, which already comes with a dedicated editor, contributing to the Generic Editor is not much valuable. From Eclipse IDE perspective, having extensions from LiclipseText can be useful for people who deliberately want to use the Generic Editor in order to combine multiple providers from multiple sources (Liclipse, language server, remote analysis...).
On the long run, it would be interesting to find out which features of the generic editor are the most missing to LiclipseText in order to replace the dedicated editor. I believe both editor share the same goal of highly factorized and reusable code editor. The Generic Editor can learn from LiclipseText and see the story of replacing LiclipseText dedicated editor as a serious criterion to prioritize work.

**Comment by fabioz** [comment]
Seems ok for me... as a note, I'll only integrate the branch when it can be compiled without errors against a stable Eclipse version (i.e.: I don't want other users which get the project to put a dependency on the dev version of Eclipse instead of a stable one, so, as soon as Oxygen is released, I'll take a look into merging this pull request).

**Comment by fabioz** [comment]
Ok, merged now that Oxygen is on RC ;)

**Pull request merged**
